language: minimal
sudo: required

services:
    - docker
    
before_install:
    - docker build -t evilbloodydemon/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true evilbloodydemon/docker-react npm run test -- --coverage